"""Default configuration values for sim_engine GUI settings."""

from __future__ import annotations

from pathlib import Path

DEFAULT_FIXED_DT = 1.0 / 60.0
DEFAULT_GRAVITY_X = 0.0
DEFAULT_GRAVITY_Z = -9810.0
DEFAULT_SOLVER_ITERATIONS = 10
DEFAULT_GROUND_Z = 0.0
DEFAULT_SEED = None

DEFAULT_SCENE = "falling_settle"
DEFAULT_FPS = 60.0
DEFAULT_MU_STATIC = 0.8
DEFAULT_MU_DYNAMIC = 0.6
DEFAULT_RESTITUTION = 0.0
DEFAULT_WINDOW_WIDTH = 1280
DEFAULT_WINDOW_HEIGHT = 720
DEFAULT_ZOOM = 1.0
DEFAULT_SHOW_AXES = True
DEFAULT_SHOW_CONTACTS = False
DEFAULT_SHOW_STATS = True
DEFAULT_RECORDING_ENABLED = False
DEFAULT_RECORDING_PATH = "simulation_capture.mp4"
DEFAULT_RECORDING_FPS = 60.0

DEFAULT_SETTINGS_PATH = Path.home() / ".sim_engine_settings.json"
